# Generated by Django 3.1.5 on 2021-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(null=True)),
                ('player1', models.TextField()),
                ('player2', models.TextField(null=True)),
                ('player1_credits', models.IntegerField(default=1000)),
                ('player2_credits', models.IntegerField(default=1000)),
                ('hand_pot', models.IntegerField(default=0)),
                ('sabacc_pot', models.IntegerField(default=0)),
            ],
        ),
    ]
