# Generated by Django 3.1.5 on 2021-04-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210425_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_player',
            field=models.TextField(default='5up3r'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='leading_player',
            field=models.TextField(default='5up3r'),
            preserve_default=False,
        ),
    ]
