# Generated by Django 3.1.5 on 2021-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210426_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player2_hand_sum',
            field=models.IntegerField(default=0),
        ),
    ]
