# Generated by Django 3.1.5 on 2021-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_player2_hand_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.TextField(default='Betting'),
        ),
    ]
