# Generated by Django 3.1.5 on 2021-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210426_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_bet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_bet',
            field=models.IntegerField(null=True),
        ),
    ]
