# Generated by Django 3.1.5 on 2021-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210426_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_bet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card10',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card11',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card12',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card13',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card14',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card15',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card16',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card17',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card18',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card19',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card2',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card20',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card21',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card22',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card23',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card24',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card25',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card26',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card27',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card28',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card29',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card3',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card30',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card31',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card32',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card33',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card34',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card35',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card36',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card37',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card38',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card39',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card4',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card40',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card41',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card42',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card43',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card44',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card45',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card46',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card47',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card48',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card49',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card5',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card50',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card51',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card52',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card53',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card54',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card55',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card56',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card57',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card58',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card59',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card6',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card60',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card61',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card62',
            field=models.IntegerField(blank=True, default=-2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card63',
            field=models.IntegerField(blank=True, default=-8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card64',
            field=models.IntegerField(blank=True, default=-11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card65',
            field=models.IntegerField(blank=True, default=-13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card66',
            field=models.IntegerField(blank=True, default=-14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card67',
            field=models.IntegerField(blank=True, default=-15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card68',
            field=models.IntegerField(blank=True, default=-17, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card69',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card7',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card70',
            field=models.IntegerField(blank=True, default=-2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card71',
            field=models.IntegerField(blank=True, default=-8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card72',
            field=models.IntegerField(blank=True, default=-11, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card73',
            field=models.IntegerField(blank=True, default=-13, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card74',
            field=models.IntegerField(blank=True, default=-14, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card75',
            field=models.IntegerField(blank=True, default=-15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card76',
            field=models.IntegerField(blank=True, default=-17, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card8',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deck_card9',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_bet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_card9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_card9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
