# Generated by Django 3.1.5 on 2021-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210426_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='followBetCounter',
            field=models.BooleanField(default=False),
        ),
    ]
