# Generated by Django 3.1.5 on 2021-04-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_followbetcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='followBetCounter',
            new_name='follow_bet_counter',
        ),
    ]
