# Generated by Django 3.1.5 on 2021-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20210427_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='follow_player_card_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='lead_player_card_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
