# Generated by Django 3.1.5 on 2021-05-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20210427_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='follow_player_shift_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='lead_player_shift_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
